// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ProgettoC_.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    [Migration("20260918142357_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Allenamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CalorieBruciate")
                        .HasColumnType("integer");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Durata")
                        .HasColumnType("integer");

                    b.Property<int>("GiornoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GiornoId");

                    b.ToTable("Allenamenti");
                });

            modelBuilder.Entity("Giorno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsWorkout")
                        .HasColumnType("boolean");

                    b.Property<int>("UtenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.ToTable("Giorni");
                });

            modelBuilder.Entity("Pasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Calorie")
                        .HasColumnType("integer");

                    b.Property<int>("Carboidrati")
                        .HasColumnType("integer");

                    b.Property<int>("GiornoId")
                        .HasColumnType("integer");

                    b.Property<int>("Grassi")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Proteine")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GiornoId");

                    b.ToTable("Pasti");
                });

            modelBuilder.Entity("Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Altezza")
                        .HasColumnType("integer");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Età")
                        .HasColumnType("integer");

                    b.Property<string>("Genere")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ObiettivoCalorieRest")
                        .HasColumnType("integer");

                    b.Property<int>("ObiettivoCalorieWorkout")
                        .HasColumnType("integer");

                    b.Property<int>("ObiettivoCarboidratiRest")
                        .HasColumnType("integer");

                    b.Property<int>("ObiettivoCarboidratiWorkout")
                        .HasColumnType("integer");

                    b.Property<int>("ObiettivoGrassiRest")
                        .HasColumnType("integer");

                    b.Property<int>("ObiettivoGrassiWorkout")
                        .HasColumnType("integer");

                    b.Property<int>("ObiettivoProteineRest")
                        .HasColumnType("integer");

                    b.Property<int>("ObiettivoProteineWorkout")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Peso")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("Allenamento", b =>
                {
                    b.HasOne("Giorno", "Giorno")
                        .WithMany("Allenamenti")
                        .HasForeignKey("GiornoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Giorno");
                });

            modelBuilder.Entity("Giorno", b =>
                {
                    b.HasOne("Utente", "Utente")
                        .WithMany("Giorni")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("Pasto", b =>
                {
                    b.HasOne("Giorno", "Giorno")
                        .WithMany("Pasti")
                        .HasForeignKey("GiornoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Giorno");
                });

            modelBuilder.Entity("Giorno", b =>
                {
                    b.Navigation("Allenamenti");

                    b.Navigation("Pasti");
                });

            modelBuilder.Entity("Utente", b =>
                {
                    b.Navigation("Giorni");
                });
#pragma warning restore 612, 618
        }
    }
}
